project_id = "iohftgaiztkzwhmwubxg"

[functions.send-report-email]
verify_jwt = false

[functions.import-google-sheet]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false